apiVersion: v1
kind: Service
metadata:
  name: sapna-service
spec:
  type: LoadBalancer
  selector:
    app: sapna-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000   # 👈 same as containerPort above
    nodePort: 31449 